# Generated by Django 4.0.1 on 2022-01-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishId', models.IntegerField()),
                ('dishName', models.CharField(max_length=100)),
                ('dishDescription', models.CharField(max_length=100)),
                ('dishPrice', models.CharField(max_length=100)),
                ('dishImage', models.ImageField(upload_to='food_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
