# Generated by Django 4.0.1 on 2022-01-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_banner_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='dishId',
            field=models.IntegerField(unique=True),
        ),
    ]
