# Generated by Django 4.0.1 on 2022-01-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_banner_dishid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishId', models.IntegerField(unique=True)),
                ('dishName', models.CharField(max_length=100)),
                ('dishDescription', models.CharField(max_length=100, null=True)),
                ('dishPrice', models.IntegerField()),
                ('dishImage', models.ImageField(upload_to='food_images/')),
                ('isBanner', models.BooleanField(default=False)),
                ('isPopular', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
