# Generated by Django 4.0.1 on 2022-01-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_menu_delete_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='searchTag',
            field=models.CharField(default=models.CharField(max_length=100), max_length=250),
        ),
    ]
