# Generated by Django 4.0.1 on 2022-01-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_menu_searchtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='searchTag',
            field=models.CharField(max_length=250),
        ),
    ]
